version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: chisel-lab
    restart: always
    environment:
      POSTGRES_DB: chisel-lab
      POSTGRES_USER: chisel-lab
      POSTGRES_PASSWORD: chisel-lab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local